"""
Prodamus Payment Integration Module

This module handles:
1. Payment link generation for Prodamus payment system
2. Webhook handling for payment notifications
3. Signature verification for security
4. User creation and course access management after successful payment
"""

import hashlib
import hmac
import json
import secrets
import urllib.parse
from datetime import datetime
from typing import Optional, Dict, Any

import aiohttp
from pydantic import BaseModel, EmailStr

# ==========================================
# CONFIGURATION
# ==========================================

# Prodamus API credentials (should be stored securely)
PRODAMUS_CONFIG = {
    "secret_key": "YOUR_SECRET_KEY_FROM_PRODAMUS",  # Secret key from Prodamus dashboard
    "shop_id": "YOUR_SHOP_ID",                       # Your shop ID
    "api_url": "https://pay.prodamus.ru",            # Prodamus payment URL
    "webhook_secret": "YOUR_WEBHOOK_SECRET",         # Secret for webhook signature verification
}

# ==========================================
# DATA MODELS
# ==========================================

class PaymentProduct(BaseModel):
    """Product in the payment request."""
    name: str
    price: int          # Price in kopecks (1 ruble = 100 kopecks)
    quantity: int = 1
    sku: Optional[str] = None


class PaymentRequest(BaseModel):
    """Payment request data."""
    order_id: str
    products: list[PaymentProduct]
    customer_email: str
    customer_phone: Optional[str] = None
    success_url: Optional[str] = None
    fail_url: Optional[str] = None
    webhook_url: Optional[str] = None
    description: Optional[str] = None
    meta: Optional[Dict[str, Any]] = None  # Additional metadata (course_id, etc.)


class ProdamusWebhookData(BaseModel):
    """Data received from Prodamus webhook."""
    order_id: str
    order_num: Optional[str] = None
    status: str
    sign: str
    customer_email: Optional[str] = None
    customer_phone: Optional[str] = None
    products: Optional[list] = None
    total_price: Optional[int] = None
    date: Optional[str] = None
    meta: Optional[Dict[str, Any]] = None


# ==========================================
# PAYMENT LINK GENERATION
# ==========================================

def generate_signature(data: dict, secret_key: str) -> str:
    """
    Generate HMAC-SHA256 signature for Prodamus request.
    
    The signature is generated by:
    1. Sorting parameters alphabetically
    2. Concatenating key-value pairs
    3. Calculating HMAC-SHA256 with secret key
    
    Args:
        data: Dictionary of parameters to sign
        secret_key: Secret key from Prodamus
    
    Returns:
        Hexadecimal signature string
    """
    # Sort parameters alphabetically
    sorted_params = sorted(data.items())
    
    # Concatenate key-value pairs
    signature_string = "&".join(f"{k}={v}" for k, v in sorted_params if v is not None)
    
    # Calculate HMAC-SHA256
    signature = hmac.new(
        secret_key.encode(),
        signature_string.encode(),
        hashlib.sha256
    ).hexdigest()
    
    return signature


def generate_payment_link(
    order_id: str,
    product_name: str,
    price_rub: int,
    customer_email: str,
    course_id: int,
    success_url: str = None,
    fail_url: str = None,
    webhook_url: str = None,
) -> str:
    """
    Generate a Prodamus payment link.
    
    This function creates a payment URL that redirects users to Prodamus
    payment page with pre-filled product and customer information.
    
    Args:
        order_id: Unique order identifier
        product_name: Name of the product (course title)
        price_rub: Price in rubles (will be converted to kopecks)
        customer_email: Customer's email for receipt
        course_id: ID of the course being purchased
        success_url: URL to redirect after successful payment
        fail_url: URL to redirect after failed payment
        webhook_url: URL for payment notifications
    
    Returns:
        Complete payment URL for Prodamus
    
    Example:
        >>> link = generate_payment_link(
        ...     order_id="ORDER-123",
        ...     product_name="Python Course",
        ...     price_rub=4990,
        ...     customer_email="user@example.com",
        ...     course_id=1
        ... )
        >>> print(link)
        https://pay.prodamus.ru/?...
    """
    # Convert price to kopecks
    price_kopecks = price_rub * 100
    
    # Build request parameters
    params = {
        "order_id": order_id,
        "customer_email": customer_email,
        "products[0][name]": product_name,
        "products[0][price]": str(price_kopecks),
        "products[0][quantity]": "1",
    }
    
    # Add optional parameters
    if success_url:
        params["success_url"] = success_url
    if fail_url:
        params["fail_url"] = fail_url
    if webhook_url:
        params["callback_url"] = webhook_url
    
    # Add metadata for webhook processing
    params["meta[course_id]"] = str(course_id)
    params["meta[email]"] = customer_email
    
    # Generate signature
    signature = generate_signature(params, PRODAMUS_CONFIG["secret_key"])
    params["sign"] = signature
    
    # Build URL
    query_string = urllib.parse.urlencode(params, safe="[]")
    payment_url = f"{PRODAMUS_CONFIG['api_url']}?{query_string}"
    
    return payment_url


def generate_payment_link_alternative(
    order_id: str,
    products: list[PaymentProduct],
    customer_email: str,
    meta: Dict[str, Any] = None,
    success_url: str = None,
    fail_url: str = None,
    webhook_url: str = None,
) -> str:
    """
    Alternative method using products list (for multiple items).
    
    Args:
        order_id: Unique order identifier
        products: List of products in the order
        customer_email: Customer's email
        meta: Additional metadata
        success_url: Redirect URL after success
        fail_url: Redirect URL after failure
        webhook_url: Webhook URL for notifications
    
    Returns:
        Complete payment URL
    """
    params = {
        "order_id": order_id,
        "customer_email": customer_email,
    }
    
    # Add products
    for i, product in enumerate(products):
        params[f"products[{i}][name]"] = product.name
        params[f"products[{i}][price]"] = str(product.price)
        params[f"products[{i}][quantity]"] = str(product.quantity)
        if product.sku:
            params[f"products[{i}][sku]"] = product.sku
    
    # Add URLs
    if success_url:
        params["success_url"] = success_url
    if fail_url:
        params["fail_url"] = fail_url
    if webhook_url:
        params["callback_url"] = webhook_url
    
    # Add metadata
    if meta:
        for key, value in meta.items():
            params[f"meta[{key}]"] = str(value)
    
    # Generate signature
    signature = generate_signature(params, PRODAMUS_CONFIG["secret_key"])
    params["sign"] = signature
    
    # Build URL
    query_string = urllib.parse.urlencode(params, safe="[]")
    return f"{PRODAMUS_CONFIG['api_url']}?{query_string}"


# ==========================================
# WEBHOOK SIGNATURE VERIFICATION
# ==========================================

def verify_webhook_signature(data: dict, signature: str, secret: str = None) -> bool:
    """
    Verify webhook signature from Prodamus.
    
    Prodamus sends a signature in the 'sign' parameter. This function
    verifies that the signature matches the expected value.
    
    Args:
        data: Complete webhook data (excluding 'sign')
        signature: Signature from webhook
        secret: Webhook secret (uses config if not provided)
    
    Returns:
        True if signature is valid, False otherwise
    """
    secret = secret or PRODAMUS_CONFIG["webhook_secret"]
    
    # Remove sign from data for verification
    data_copy = {k: v for k, v in data.items() if k != "sign"}
    
    # Calculate expected signature
    expected_signature = generate_signature(data_copy, secret)
    
    # Compare signatures (constant-time comparison)
    return hmac.compare_digest(signature.lower(), expected_signature.lower())


# ==========================================
# ORDER ID GENERATION
# ==========================================

def generate_order_id(course_id: int, user_email: str) -> str:
    """
    Generate a unique order ID.
    
    Format: LMS-{timestamp}-{random}-{course_id}
    
    Args:
        course_id: ID of the course
        user_email: User's email
    
    Returns:
        Unique order ID string
    """
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    random_part = secrets.token_hex(4)
    return f"LMS-{timestamp}-{random_part}-C{course_id}"


# ==========================================
# PAYMENT PROCESSING
# ==========================================

async def process_successful_payment(webhook_data: dict) -> Dict[str, Any]:
    """
    Process a successful payment webhook from Prodamus.
    
    This function:
    1. Verifies the webhook signature
    2. Creates or retrieves the user
    3. Grants access to the purchased course
    4. Sends welcome email with credentials (if new user)
    
    Args:
        webhook_data: Complete webhook data from Prodamus
    
    Returns:
        Dictionary with processing result
    
    Raises:
        ValueError: If signature verification fails
        Exception: If database operations fail
    """
    from database import (
        create_user,
        get_user_by_email,
        purchase_course,
        get_course_by_id,
    )
    
    # Extract signature
    signature = webhook_data.get("sign", "")
    
    # Verify signature
    if not verify_webhook_signature(webhook_data, signature):
        raise ValueError("Invalid webhook signature")
    
    # Extract payment data
    order_id = webhook_data.get("order_id", "")
    status = webhook_data.get("status", "")
    customer_email = webhook_data.get("customer_email", "")
    total_price = webhook_data.get("total_price", 0)  # In kopecks
    
    # Get metadata
    meta = webhook_data.get("meta", {})
    course_id = meta.get("course_id") or webhook_data.get("meta[course_id]")
    
    if not course_id:
        # Try to extract from order_id (format: LMS-...-C{course_id})
        if "C" in order_id:
            try:
                course_id = int(order_id.split("C")[-1])
            except ValueError:
                pass
    
    if not course_id:
        raise ValueError("Course ID not found in payment data")
    
    # Verify payment status
    if status.lower() not in ["success", "paid", "completed"]:
        return {
            "success": False,
            "message": f"Payment status is '{status}', not processing"
        }
    
    # Get course info
    course = get_course_by_id(int(course_id))
    if not course:
        raise ValueError(f"Course {course_id} not found")
    
    # Get or create user
    user = get_user_by_email(customer_email)
    is_new_user = False
    generated_password = None
    
    if not user:
        # Create new user with random password
        generated_password = secrets.token_urlsafe(12)
        user = create_user(
            email=customer_email,
            password=generated_password,
            role="user"
        )
        is_new_user = True
    
    # Grant course access
    try:
        purchase = purchase_course(
            user_id=user["id"],
            course_id=int(course_id),
            payment_id=order_id,
            amount_rub=total_price // 100,  # Convert to rubles
            payment_status="completed"
        )
    except ValueError as e:
        # User already has access
        return {
            "success": True,
            "message": str(e),
            "user_id": user["id"],
            "course_id": course_id
        }
    
    # TODO: Send welcome email with credentials for new users
    # await send_welcome_email(user["email"], generated_password, course["title"])
    
    return {
        "success": True,
        "message": "Payment processed successfully",
        "user_id": user["id"],
        "course_id": course_id,
        "is_new_user": is_new_user,
        "generated_password": generated_password if is_new_user else None
    }


# ==========================================
# EXAMPLE USAGE
# ==========================================

if __name__ == "__main__":
    # Example: Generate a payment link
    order_id = generate_order_id(course_id=1, user_email="student@example.com")
    
    payment_link = generate_payment_link(
        order_id=order_id,
        product_name="Python для начинающих",
        price_rub=4990,
        customer_email="student@example.com",
        course_id=1,
        success_url="https://your-lms.com/payment/success",
        fail_url="https://your-lms.com/payment/fail",
        webhook_url="https://your-lms.com/prodamus-webhook"
    )
    
    print("=" * 60)
    print("Prodamus Payment Link Generator")
    print("=" * 60)
    print(f"\nOrder ID: {order_id}")
    print(f"\nPayment URL:\n{payment_link}")
    print("\n" + "=" * 60)
